### ISSUE TITLE
Frozen Annotald

### ISSUE THREAD

**Issue by rtruswell** [Annotald/annotald#89]
Helpful bug report: Annotald won't let me do anything today (last used roughly a week ago). It doesn't mark IPs in a different colour like it used to, but otherwise looks much like usual (in Chrome and the log in the terminal).

Sorry this is so vague but that's literally all I know.

I did see some errors in the Chrome javascript console -- see attached screenshot

[JS_console.pdf](https://github.com/Annotald/annotald/files/848200/JS_console.pdf)

**Comment by aecay** [comment]
The javascript errors make it look like chrome is barfing on a javascript library that's part of annotald (but not actually written by me -- annotald uses it as a building block).  This is weird.  The first thing I have to ask is whether you've changed anything since you last used annotald successfully.  

It could be that a new version of Chrome (which generally updates itself silently) has introduced an incompatibility.  That doesn't usually happen, but just in case, what's your chrome version?  (Navigate to chrome://help and find the version number there)

You could also try uninstalling and reinstalling Annotald, in case a mystical cosmic ray hit your hard drive and corrupted the JS file.  For that, `pip uninstall --user annotald` followed by `pip install --user annotald`.

**Comment by rtruswell** [comment]
Chrome version  56.0.2924.87 (64-bit) (but now you mention it, it's updating...).  This is my work computer -- I'll get a second opinion from my laptop tonight.

It had occurred to me that this might be a Chrome problem.  I guess I could try clearing browsing data from Chrome and seeing if that helps.

But no, no other recent changes.

I tried pip install --upgrade annotald in response to the problem before flagging this.  Will try uninstall / install later.

**Comment by rtruswell** [comment]
It WAS a Chrome problem.  Still not sure what, but clearing all my browsing data fixed it.  As you were -- sorry to trouble you.
